DSPBRIDGE: checkpatch - space required after comma
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Omar Ramirez Luna <omar.ramirez@ti.com>